### ISSUE TITLE
Use the panel-extensions template setup?

### ISSUE THREAD

**Issue by droumis** [d-v-b/panel-neuroglancer#2]
I have not yet contributed to the panel-extensions org, but I see that there are some guidelines already: https://github.com/panel-extensions/copier-template-panel-extension?tab=readme-ov-file

Just noting the difference with this repo and raising the question of how important it is to follow that template and use pixi etc.

@philippjfr ?

**Comment by d-v-b** [comment]
i'm happy to follow the template!

**Comment by droumis** [comment]
Philipp (panel author) says following setting things up via template is not high priority at the moment so it shouldn't be a blocker for initial release

**Comment by philippjfr** [comment]
Yeah I don't think it's a an issue. I'm adding the CI config now. The panel extension template also makes some assumptions about build infrastructure which isn't needed here.
